removing .github from .prettierignore (#7044)
supersedes: https://github.com/HereNotThere/harmony/pull/7026

diff --git a/.github/workflows/Notification_service_docker.yml b/.github/workflows/Notification_service_docker.yml
--- a/.github/workflows/Notification_service_docker.yml
+++ b/.github/workflows/Notification_service_docker.yml
@@ -36,24 +36,24 @@ jobs:
         steps:
             - name: Set Environment Variables
               env:
-                BRANCH_NAME: ${{ github.ref }}
-                ENVIRONMENT_NAME_INPUT: ${{ github.event.inputs.environment_name }}
+                  BRANCH_NAME: ${{ github.ref }}
+                  ENVIRONMENT_NAME_INPUT: ${{ github.event.inputs.environment_name }}
               run: |
-                # if ENVIROMENT_NAME_INPUT is set, set ENV_NAME to it.
-                # else if branch is main, set ENV_NAME to gamma.
-                # else if branch is omega, set ENV_NAME to omega.
-                # else  (branch is neither), exit with error.
+                  # if ENVIROMENT_NAME_INPUT is set, set ENV_NAME to it.
+                  # else if branch is main, set ENV_NAME to gamma.
+                  # else if branch is omega, set ENV_NAME to omega.
+                  # else  (branch is neither), exit with error.
 
-                if [ -n "$ENVIRONMENT_NAME_INPUT" ]; then
-                  echo "ENV_NAME=$ENVIRONMENT_NAME_INPUT" >> $GITHUB_ENV
-                elif [ $BRANCH_NAME = "refs/heads/main" ]; then
-                  echo "ENV_NAME=gamma" >> $GITHUB_ENV
-                elif [ $BRANCH_NAME = "refs/heads/omega" ]; then
-                  echo "ENV_NAME=omega" >> $GITHUB_ENV
-                else
-                  echo "Error: Branch name is not main or omega. Exiting."
-                  exit 1
-                fi
+                  if [ -n "$ENVIRONMENT_NAME_INPUT" ]; then
+                    echo "ENV_NAME=$ENVIRONMENT_NAME_INPUT" >> $GITHUB_ENV
+                  elif [ $BRANCH_NAME = "refs/heads/main" ]; then
+                    echo "ENV_NAME=gamma" >> $GITHUB_ENV
+                  elif [ $BRANCH_NAME = "refs/heads/omega" ]; then
+                    echo "ENV_NAME=omega" >> $GITHUB_ENV
+                  else
+                    echo "Error: Branch name is not main or omega. Exiting."
+                    exit 1
+                  fi
 
             - name: Checkout
               uses: actions/checkout@v4
@@ -61,33 +61,33 @@ jobs:
             - name: Setup AWS Credentials
               uses: aws-actions/configure-aws-credentials@v4
               with:
-                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-                aws-region: us-east-1
+                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+                  aws-region: us-east-1
 
             - name: Login to Amazon ECR
               id: login-aws-ecr
               uses: aws-actions/amazon-ecr-login@v2
               with:
-                registry-type: 'public'
+                  registry-type: 'public'
 
             - name: Build and push docker image to Amazon ECR
               env:
-                ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}
-                #This can be custom alias once requested to aws and approved for public repo
-                REGISTRY_ALIAS: l8h0l2e6
-                ECR_REPOSITORY: notification-service
+                  ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}
+                  #This can be custom alias once requested to aws and approved for public repo
+                  REGISTRY_ALIAS: l8h0l2e6
+                  ECR_REPOSITORY: notification-service
               run: |
-                docker build -t $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:latest . -f ./servers/notification-service/Dockerfile
-                docker push $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:latest
+                  docker build -t $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:latest . -f ./servers/notification-service/Dockerfile
+                  docker push $ECR_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:latest
 
             - name: Deploy to ECS
               run: './scripts/deploy-latest-notification-service.sh'
               env:
-                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-                AWS_REGION: us-east-1
-                ENVIRONMENT_NAME: ${{ env.ENV_NAME }}
+                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+                  AWS_REGION: us-east-1
+                  ENVIRONMENT_NAME: ${{ env.ENV_NAME }}
 
             # If action failed, we send a slack notification
             - name: Slack notification
diff --git a/.github/workflows/Render_deploy.yml b/.github/workflows/Render_deploy.yml
--- a/.github/workflows/Render_deploy.yml
+++ b/.github/workflows/Render_deploy.yml
@@ -1,91 +1,91 @@
-name: "Render_deploy"
+name: 'Render_deploy'
 
 on:
-  workflow_dispatch:
-    inputs:
-      environment_name:
-        description: "Environment name"
-        required: true
-        type: choice
-        options:
-          - "gamma"
-          - "omega"
-        default: "gamma"
+    workflow_dispatch:
+        inputs:
+            environment_name:
+                description: 'Environment name'
+                required: true
+                type: choice
+                options:
+                    - 'gamma'
+                    - 'omega'
+                default: 'gamma'
 
-  push: 
-    branches:
-      - main
-      - omega
+    push:
+        branches:
+            - main
+            - omega
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+    group: ${{ github.workflow }}-${{ github.ref }}
+    cancel-in-progress: true
 
 jobs:
-  deploy:
-    name: Deploy to Render
-    runs-on: ubuntu-latest
+    deploy:
+        name: Deploy to Render
+        runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
 
-      - name: Set up Environment Variables
-        run: |
-          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-              ENVIRONMENT_NAME=${{ github.event.inputs.environment_name }}
-          elif [ "${{ github.event_name }}" == "push" ]; then
-            # If the branch is omega, we deploy to omega environment
-            if [ "${{ github.ref }}" == "refs/heads/omega" ]; then
-                ENVIRONMENT_NAME="omega"
-            elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
-                ENVIRONMENT_NAME="gamma"
-            else
-                echo "Environment name not set"
-                exit 1
-            fi
-          fi
+            - name: Set up Environment Variables
+              run: |
+                  if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+                      ENVIRONMENT_NAME=${{ github.event.inputs.environment_name }}
+                  elif [ "${{ github.event_name }}" == "push" ]; then
+                    # If the branch is omega, we deploy to omega environment
+                    if [ "${{ github.ref }}" == "refs/heads/omega" ]; then
+                        ENVIRONMENT_NAME="omega"
+                    elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
+                        ENVIRONMENT_NAME="gamma"
+                    else
+                        echo "Environment name not set"
+                        exit 1
+                    fi
+                  fi
 
-          echo "Environment name is $ENVIRONMENT_NAME"
+                  echo "Environment name is $ENVIRONMENT_NAME"
 
-          # set the HARMONY_WEB_WEBHOOK_URL based on environment name
-          if [ "$ENVIRONMENT_NAME" == "gamma" ]; then
-            HARMONY_WEB_WEBHOOK_URL="${{ secrets.HARMONY_WEB_WEBHOOK_URL_GAMMA }}"
-            HARMONY_WEB_SERVICE_ID="${{ secrets.HARMONY_WEB_SERVICE_ID_GAMMA }}"
-          elif [ "$ENVIRONMENT_NAME" == "omega" ]; then
-            HARMONY_WEB_WEBHOOK_URL="${{ secrets.HARMONY_WEB_WEBHOOK_URL_OMEGA }}"
-            HARMONY_WEB_SERVICE_ID="${{ secrets.HARMONY_WEB_SERVICE_ID_OMEGA }}"
-          else
-            echo "Environment name not recognized: $ENVIRONMENT_NAME"
-            exit 1
-          fi
-          
+                  # set the HARMONY_WEB_WEBHOOK_URL based on environment name
+                  if [ "$ENVIRONMENT_NAME" == "gamma" ]; then
+                    HARMONY_WEB_WEBHOOK_URL="${{ secrets.HARMONY_WEB_WEBHOOK_URL_GAMMA }}"
+                    HARMONY_WEB_SERVICE_ID="${{ secrets.HARMONY_WEB_SERVICE_ID_GAMMA }}"
+                  elif [ "$ENVIRONMENT_NAME" == "omega" ]; then
+                    HARMONY_WEB_WEBHOOK_URL="${{ secrets.HARMONY_WEB_WEBHOOK_URL_OMEGA }}"
+                    HARMONY_WEB_SERVICE_ID="${{ secrets.HARMONY_WEB_SERVICE_ID_OMEGA }}"
+                  else
+                    echo "Environment name not recognized: $ENVIRONMENT_NAME"
+                    exit 1
+                  fi
 
-          echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_ENV
-          echo "RENDER_BEARER_TOKEN=${{ secrets.RENDER_BEARER_TOKEN }}" >> $GITHUB_ENV
-          echo "HARMONY_WEB_SERVICE_ID=$HARMONY_WEB_SERVICE_ID" >> $GITHUB_ENV
-          echo "HARMONY_WEB_WEBHOOK_URL=$HARMONY_WEB_WEBHOOK_URL" >> $GITHUB_ENV
 
-      - name: Deploy Render Web App
-        env:
-          HARMONY_WEB_WEBHOOK_URL: ${{ env.HARMONY_WEB_WEBHOOK_URL }}
-          HARMONY_WEB_SERVICE_ID: ${{ env.HARMONY_WEB_SERVICE_ID }}
-          RENDER_BEARER_TOKEN: ${{ secrets.RENDER_BEARER_TOKEN }}
-        run: ./scripts/deploy-harmony-web.sh
+                  echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_ENV
+                  echo "RENDER_BEARER_TOKEN=${{ secrets.RENDER_BEARER_TOKEN }}" >> $GITHUB_ENV
+                  echo "HARMONY_WEB_SERVICE_ID=$HARMONY_WEB_SERVICE_ID" >> $GITHUB_ENV
+                  echo "HARMONY_WEB_WEBHOOK_URL=$HARMONY_WEB_WEBHOOK_URL" >> $GITHUB_ENV
 
-      # If CI failed, we send a slack notification
-      - name: Alert notification
-        if: failure()
-        uses: slackapi/slack-github-action@v1.24.0
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL || secrets.SLACK_CD_ALERT_WORKFLOW_WEBHOOK_URL }}
-        with:
-          payload: |
-            {
-                "step": "Deploy Render Web App",
-                "environment": "${{ env.ENVIRONMENT_NAME }}",
-                "branch": "${{ github.ref }}",
-                "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
-                "commit": "${{ github.sha }}",
-                "actor": "${{ github.actor }}"
-            }
+            - name: Deploy Render Web App
+              env:
+                  HARMONY_WEB_WEBHOOK_URL: ${{ env.HARMONY_WEB_WEBHOOK_URL }}
+                  HARMONY_WEB_SERVICE_ID: ${{ env.HARMONY_WEB_SERVICE_ID }}
+                  RENDER_BEARER_TOKEN: ${{ secrets.RENDER_BEARER_TOKEN }}
+              run: ./scripts/deploy-harmony-web.sh
+
+            # If CI failed, we send a slack notification
+            - name: Alert notification
+              if: failure()
+              uses: slackapi/slack-github-action@v1.24.0
+              env:
+                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL || secrets.SLACK_CD_ALERT_WORKFLOW_WEBHOOK_URL }}
+              with:
+                  payload: |
+                      {
+                          "step": "Deploy Render Web App",
+                          "environment": "${{ env.ENVIRONMENT_NAME }}",
+                          "branch": "${{ github.ref }}",
+                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+                          "commit": "${{ github.sha }}",
+                          "actor": "${{ github.actor }}"
+                      }
diff --git a/.github/workflows/River_deploy.yml b/.github/workflows/River_deploy.yml
--- a/.github/workflows/River_deploy.yml
+++ b/.github/workflows/River_deploy.yml
@@ -79,10 +79,10 @@ jobs:
 
             - name: Debug Log
               run: |
-                echo "Deploying to environment: ${{ inputs.environment_name }}"
-                echo "with image tag: ${{ inputs.docker_image_tag }}"
-                echo "to nodes: ${{ inputs.node_numbers }}"
-                echo "using public ECR URL: ${{ inputs.public_ecr_url }}"
+                  echo "Deploying to environment: ${{ inputs.environment_name }}"
+                  echo "with image tag: ${{ inputs.docker_image_tag }}"
+                  echo "to nodes: ${{ inputs.node_numbers }}"
+                  echo "using public ECR URL: ${{ inputs.public_ecr_url }}"
 
             - name: Configure AWS credentials
               uses: aws-actions/configure-aws-credentials@v4
@@ -93,18 +93,18 @@ jobs:
 
             - name: Check if image exists
               env:
-                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
               run: |
-                # Don't run the check for transient environments.
-                if grep -q "transient" <<< "${{ inputs.docker_image_tag }}"; then
-                    echo "Transient deploy detected. Not running image checks."
-                elif ! docker manifest inspect public.ecr.aws/h5v6m2x1/river:${{ inputs.docker_image_tag }} > /dev/null 2>&1; then
-                    echo "Docker image with the tag=${{ inputs.docker_image_tag }} does not exist. No need to deploy river."
-                    exit 1 # fail the job, this is an error, don't call this with a image that doesn't exist
-                else
-                    echo "Docker image with the tag=${{ inputs.docker_image_tag }} exists. Continue with the deployment."
-                fi
+                  # Don't run the check for transient environments.
+                  if grep -q "transient" <<< "${{ inputs.docker_image_tag }}"; then
+                      echo "Transient deploy detected. Not running image checks."
+                  elif ! docker manifest inspect public.ecr.aws/h5v6m2x1/river:${{ inputs.docker_image_tag }} > /dev/null 2>&1; then
+                      echo "Docker image with the tag=${{ inputs.docker_image_tag }} does not exist. No need to deploy river."
+                      exit 1 # fail the job, this is an error, don't call this with a image that doesn't exist
+                  else
+                      echo "Docker image with the tag=${{ inputs.docker_image_tag }} exists. Continue with the deployment."
+                  fi
 
             # Send a slack notification before deploying if the environment is gamma
             - name: Info notification
@@ -161,13 +161,13 @@ jobs:
               if: failure()
               working-directory: ./infra
               env:
-                ENV: '${{ inputs.environment_name }}'
-                TF_ACTION_TYPE: "Riverdeploy"
-                TF_STATUS: "ERROR"
-                LOG_MESSAGE: "River deploy to ECS failed for ${{ github.ref }} branch (https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
-                TF_VAR_datadog_api_key: ${{ secrets.TF_VAR_datadog_api_key }}
-                TF_VAR_datadog_app_key: ${{ secrets.TF_VAR_datadog_app_key }}
-              run: "./log_datadog.sh"
+                  ENV: '${{ inputs.environment_name }}'
+                  TF_ACTION_TYPE: 'Riverdeploy'
+                  TF_STATUS: 'ERROR'
+                  LOG_MESSAGE: 'River deploy to ECS failed for ${{ github.ref }} branch (https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
+                  TF_VAR_datadog_api_key: ${{ secrets.TF_VAR_datadog_api_key }}
+                  TF_VAR_datadog_app_key: ${{ secrets.TF_VAR_datadog_app_key }}
+              run: './log_datadog.sh'
 
     on_failure:
         name: On Failure
@@ -216,12 +216,12 @@ jobs:
               env:
                   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CD_INFO_WORKFLOW_WEBHOOK_URL }}
               with:
-                payload: |
-                    {
-                        "message": "Deploy job ran successfully for docker tag: ${{ inputs.docker_image_tag }} on nodes: ${{ inputs.node_numbers }}",
-                        "environment": "${{ inputs.environment_name }}",
-                        "branch": "${{ github.ref }}",
-                        "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
-                        "commit": "${{ github.sha }}",
-                        "actor": "${{ github.actor }}"
-                    }
+                  payload: |
+                      {
+                          "message": "Deploy job ran successfully for docker tag: ${{ inputs.docker_image_tag }} on nodes: ${{ inputs.node_numbers }}",
+                          "environment": "${{ inputs.environment_name }}",
+                          "branch": "${{ github.ref }}",
+                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+                          "commit": "${{ github.sha }}",
+                          "actor": "${{ github.actor }}"
+                      }
diff --git a/.github/workflows/Workers_deploy.yml b/.github/workflows/Workers_deploy.yml
--- a/.github/workflows/Workers_deploy.yml
+++ b/.github/workflows/Workers_deploy.yml
@@ -35,24 +35,24 @@ jobs:
         steps:
             - name: Set Environment Variables
               env:
-                BRANCH_NAME: ${{ github.ref }}
-                ENVIRONMENT_NAME_INPUT: ${{ github.event.inputs.environment_name }}
+                  BRANCH_NAME: ${{ github.ref }}
+                  ENVIRONMENT_NAME_INPUT: ${{ github.event.inputs.environment_name }}
               run: |
-                # if ENVIROMENT_NAME_INPUT is set, set ENV_NAME to it.
-                # else if branch is main, set ENV_NAME to test-beta.
-                # else if branch is omega, set ENV_NAME to omega.
-                # else  (branch is neither), exit with error.
+                  # if ENVIROMENT_NAME_INPUT is set, set ENV_NAME to it.
+                  # else if branch is main, set ENV_NAME to test-beta.
+                  # else if branch is omega, set ENV_NAME to omega.
+                  # else  (branch is neither), exit with error.
 
-                if [ -n "$ENVIRONMENT_NAME_INPUT" ]; then
-                  echo "ENV_NAME=$ENVIRONMENT_NAME_INPUT" >> $GITHUB_ENV
-                elif [ $BRANCH_NAME = "refs/heads/main" ]; then
-                  echo "ENV_NAME=test-beta" >> $GITHUB_ENV
-                elif [ $BRANCH_NAME = "refs/heads/omega" ]; then
-                  echo "ENV_NAME=omega" >> $GITHUB_ENV
-                else
-                  echo "Error: Branch name is not main or omega. Exiting."
-                  exit 1
-                fi
+                  if [ -n "$ENVIRONMENT_NAME_INPUT" ]; then
+                    echo "ENV_NAME=$ENVIRONMENT_NAME_INPUT" >> $GITHUB_ENV
+                  elif [ $BRANCH_NAME = "refs/heads/main" ]; then
+                    echo "ENV_NAME=test-beta" >> $GITHUB_ENV
+                  elif [ $BRANCH_NAME = "refs/heads/omega" ]; then
+                    echo "ENV_NAME=omega" >> $GITHUB_ENV
+                  else
+                    echo "Error: Branch name is not main or omega. Exiting."
+                    exit 1
+                  fi
 
             - name: Checkout
               uses: actions/checkout@v4
