Fail the river deploy script if the docker image doesn’t exist (#6261)
Now that we’re building images on every commit if this happens its an
error and we should know about it.

diff --git a/.github/workflows/River_deploy.yml b/.github/workflows/River_deploy.yml
--- a/.github/workflows/River_deploy.yml
+++ b/.github/workflows/River_deploy.yml
@@ -87,6 +87,7 @@ jobs:
 
                     # set a github env var to skip the next step
                     echo "SKIP_DEPLOY=true" >> $GITHUB_ENV
+                    exit 1 # fail the job, this is an error, don't call this with a image that doesn't exist
                 else 
                     echo "Docker image with the tag=${{ inputs.docker_image_tag }} exists. Continue with the deployment."
                 fi
