Add specific load test title in failure notification (#4883)

diff --git a/.github/workflows/SDK_load_tests.yml b/.github/workflows/SDK_load_tests.yml
--- a/.github/workflows/SDK_load_tests.yml
+++ b/.github/workflows/SDK_load_tests.yml
@@ -19,7 +19,8 @@ jobs:
                 image: redis:latest
                 ports:
                     - '6379:6379'
-
+        env:
+            LAST_FAILED_STEP: ""
         steps:
             - name: Checkout code
               uses: actions/checkout@v3
@@ -53,23 +54,28 @@ jobs:
               run: |
                 export LOAD_TEST_PATH="./casablanca/sdk"
                 export TEST_CMD="yarn test:ci:load-tests-s2"
-                ./scripts/run-and-publish-load-test-metrics.sh
+                ./scripts/run-and-publish-load-test-metrics.sh || (echo "Test failed, setting LAST_FAILED_STEP" && echo "LAST_FAILED_STEP=Run Load Tests S2" >> $GITHUB_ENV && exit 1)
             - name: Run Load Tests S3
               if: github.event.schedule == '0 10 * * *'
-              run: yarn test:ci:load-tests-s3
+              run: |
+                yarn test:ci:load-tests-s3 || (echo "Test failed, setting LAST_FAILED_STEP" && echo "LAST_FAILED_STEP=Run Load Tests S3" >> $GITHUB_ENV && exit 1)
+        
             - name: Run Load Tests S3.1
               if: github.event.schedule == '0 11 * * *'
-              run: yarn test:ci:load-tests-s3.1
+              run: |
+                yarn test:ci:load-tests-s3.1 || (echo "Test failed, setting LAST_FAILED_STEP" && echo "LAST_FAILED_STEP=Run Load Tests S3.1" >> $GITHUB_ENV && exit 1)
+      
             - name: Run Load Tests S4.1
               if: github.event.schedule == '0 12 * * *'
-              run: yarn test:ci:load-tests-s4.1
+              run: |
+                yarn test:ci:load-tests-s4.1 || (echo "Test failed, setting LAST_FAILED_STEP" && echo "LAST_FAILED_STEP=Run Load Tests S4.1" >> $GITHUB_ENV && exit 1)
             # If failed, we send a slack notification
             - name: Slack notification
               if: failure()
               uses: rtCamp/action-slack-notify@v2
               env:
                   SLACK_WEBHOOK: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK_URL }}
-                  SLACK_TITLE: 'Failure'
+                  SLACK_TITLE: 'Failure in ${{ env.LAST_FAILED_STEP }}'
                   SLACK_USERNAME: 'Load Tests'
                   SLACK_ICON_EMOJI: ':test_tube:'
                   SLACK_COLOR: '#FF0000'
